apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations: {}
  labels:
    app: ratings
    app.kubernetes.io/component: ratings
    app.kubernetes.io/instance: ratings
  name: ratings
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: ratings:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: migrating-apps-v3/1.1
      uri: https://github.com/rh-tstockwell/bookinfo-ratings.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:10
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: teGQRFtH9DQTQO3Fwhu5
    type: GitHub
  - generic:
      secret: QlTal-G7LyCn7u5DVhOh
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
