apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations: {}
  labels:
    app: ratings
    app.kubernetes.io/component: ratings
    app.kubernetes.io/instance: ratings
  name: ratings
spec:
  lookupPolicy:
    local: false
